import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './../components/Header';
import Footer from './../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header className="header"><Header/></header>
      <body className={inter.className}>        
        {children}        
      </body>
      <footer className="footer"><Footer/></footer>
      <style>{`
      .header {
        position: fixed;
        top: 0px;
        left:0;
        right:0;
      }
      .footer {
        position:fixed;
        bottom:0;
        left:0;
        right:0;
        height:35px;
      }
    `}</style>
    </html>
  )
}
